### ISSUE TITLE
"Limit to current window" option inconsisently displayed with large number of windows and tabs

### ISSUE THREAD

**Issue by exterrestris** [alct/export-tabs-urls#8]
The option to limit the tabs exported to the current windows seems to have been removed with the latest version

**Comment by alct** [comment]
Hello,

Thank you for your feedback :)

Could you please provide me with some info about:

* your Operating System and Firefox version
* the number of Firefox windows open
* is the option missing on every window? a specific one?

(note that the option is only shown when there are actually several windows open)

**Comment by exterrestris** [comment]
Firefox 65 on Windows 10.
20+ windows open with ~470 tabs (unevenly distributed).
It's only missing on certain windows - no obvious pattern that I can see. It also seems to appear on windows it's missing from if the drop-down is closed and re-opened - sometimes straight away, other times after closing and re-opening two or three times.

**Comment by alct** [comment]
Does reverting to the [previous version (0.1.13)](https://addons.mozilla.org/firefox/downloads/file/1012657/export_tabs_urls-0.1.13-an+fx-windows.xpi) fix the issue? (you must uninstall the current one first)

**Comment by exterrestris** [comment]
Just given that a try, and reverting to 0.1.13 doesn't fix it - the option is still missing from some windows initially, but closing and re-opening makes it appear

**Comment by alct** [comment]
Here is a patched version, could you please give it a try? I have tried another method in other to get the number of open windows (and thus determine whether the "Limit to current window" option should be displayed or not).

1. Download the patched version either with another web browser or via de CLI (otherwise, Firefox will try to install it and run into an error)
2. In Firefox, go to `about:debugging` and enable "Add-on debugging"
3. Click on "Load Temporary Add-on..." and chose the patched version you just downloaded

The patched version will be added to your toolbar (I have added a striped black and yellow ribbon to the main popup in order to help differentiating it). Does this version fix the issue?

(regardless of whether it fixed the issue or not, uninstall this beta version when you are done testing)

Thank you for your help!

**Edit:** the link to the patched version has been removed, the fix has been released in version 0.2.1

**Comment by exterrestris** [comment]
Yep, that looks to have resolved it.

**Comment by alct** [comment]
Great!

I will give it some more testing and if it works reliably, I will include the patch in the next release.

Thank you again for your help.

**Comment by alct** [comment]
Fixed in 0.2.1, see fd113d4ed0cfaaf6f44455ad7627079d1baeca0f.
